services:
  - type: web
    name: aqi-api
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    plan: free
    envVars:
      - key: MODEL_PATH
        value: models/best_model.pkl
      - key: DATA_PATH
        value: data/processed/processed_data.csv